[project]
name = "pdf-combiner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "comtypes>=1.4.13",
    "openpyxl>=3.1.5",
    "pypdf>=6.1.2",
    "reportlab>=4.4.4",
]
